server:
  servlet:
    context-path: /demo
  port: 8888
debug: false

spring:
  profiles:
    active: dev
  data:
    mongodb:
#      database: firstDB
#      host: 127.0.0.1
#      port: 27017
#      username: arh
#      password: 123
      uri: mongodb://arh:123@127.0.0.1:27017/firstDB

anno:
  configuration:
    properties:
      testName: config_test_Don



