use:
  dynamicDataSource: true

logging:
  file:
    name: C:\DougLea\IdeaProjects\MyLog\springBootDemoLog\myLog.log
  level:
    root: info
    com.arh.springbootdemo: debug
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    validationQuery: select 1 from dual
    #监控
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

datasource:
  business:
    url: jdbc:mysql://192.168.31.37:3306/business_database?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
  user:
    url: jdbc:mysql://192.168.31.37:3306/user_database?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
