create table T_USER(
	F_ID INT(11) NOT NULL AUTO_INCREMENT,
	F_NAME VARCHAR(50),
	F_BIRTHDAY DATETIME,
	F_EMAIL varchar(50),
	F_INFO VARCHAR(200),
	F_ADD_USER INT(11),
	F_ADD_DATE DATETIME,
	F_UPDATE_USER INT(11),
	F_UPDATE_DATE DATETIME,
	PRIMARY KEY (F_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;